title: [MadQt]
description: [Tutorials and Tools for PyQt and PySide]
remote_theme: pmarsceill/just-the-docs
color_scheme: "mpi"

# Aux links for the upper right navigation
aux_links:
  "MadQt on GitHub":
    - "//github.com/MadPonyInteractive/MadQt"


# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 3
